(ns majrix.handler
  "Server definition"
  (:require [compojure.core :refer :all]
            [compojure.route :as route]
            [ring.middleware.defaults :refer [wrap-defaults site-defaults]]))

; Comments with one semi-colon will not appear in the documentation generated by marginalia 
;; Comments with two semi-colons will appear in the documentation
;; ## Inputs 
;; none
(defn examplefunc
  "This comment should show on the lefthand side of the docs

  ## Markup examples ##

  `rm -rf /`

  - item one
  - item two
  "
  []
  "Hello World")

(defroutes app-routes
  (GET "/" [] (examplefunc))
  (route/not-found "Not Found"))

(def app
  (wrap-defaults app-routes site-defaults))
